version: '3.8'

services:
  # Serviço do PostgreSQL
  postgres:
    image: postgres:latest
    container_name: UserPostgres
    restart: always
    environment:
      POSTGRES_DB: MyDatabase
      POSTGRES_USER: MyUsername
      POSTGRES_PASSWORD: MyPassword
    ports:
      - "5100:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Serviço do Spring Boot (userservice)
  userservice:
    image: wiliian/user-service:v1
    container_name: userService
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/MyDatabase
      DATABASE_USERNAME: MyUsername
      DATABASE_PASSWORD: MyPassword
      SPRING_PROFILES_ACTIVE: prod

volumes:
  pgdata:
